#Hugo configuration
title = "Test Reserved Folders"
baseURL = "https:\/\/testreservedfolders.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758904"
subfolder = ""
